/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ui;

import com.mycompany.helper.ShareData;
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/**
 *
 * @author MMC
 */
public class MainForm extends javax.swing.JFrame {

    private QLSV1 qlsv1;
    private QLDiem1 diem1;

    //private Login login;
    public MainForm() {
        initComponents();
        setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);//phóng to tối đa kích thước của form
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tbrDangNhap = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        tbrAbout = new javax.swing.JButton();
        tbpMain = new javax.swing.JTabbedPane();
        jSeparator1 = new javax.swing.JSeparator();
        lblName = new javax.swing.JLabel();
        lblVaiTro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuDangXuat = new javax.swing.JMenuItem();
        menuThoat = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuQLSV = new javax.swing.JMenuItem();
        menuQLD = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuNoiDung = new javax.swing.JMenuItem();
        menuGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jToolBar1.setRollover(true);

        tbrDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-32.png"))); // NOI18N
        tbrDangNhap.setText("Đăng Nhập");
        tbrDangNhap.setFocusable(false);
        tbrDangNhap.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrDangNhap.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrDangNhapActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrDangNhap);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Person-Male-Light-icon-24.png"))); // NOI18N
        jButton2.setText("Quản Lý Sinh Viên");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton2);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        jButton3.setText("Quản Lý Điểm");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton3);

        tbrAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Telephone.png"))); // NOI18N
        tbrAbout.setText("Giới Thiệu");
        tbrAbout.setFocusable(false);
        tbrAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbrAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbrAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbrAboutActionPerformed(evt);
            }
        });
        jToolBar1.add(tbrAbout);

        lblName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        lblVaiTro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jMenu1.setText("Hệ Thống");

        menuDangXuat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/logout-icon-16.png"))); // NOI18N
        menuDangXuat.setText("Đăng Nhập");
        menuDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDangXuatActionPerformed(evt);
            }
        });
        jMenu1.add(menuDangXuat);

        menuThoat.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Button-Close-icon-16.png"))); // NOI18N
        menuThoat.setText("Thoát");
        menuThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuThoatActionPerformed(evt);
            }
        });
        jMenu1.add(menuThoat);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Quản Lý");

        menuQLSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuQLSV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Person-Male-Light-icon-16.png"))); // NOI18N
        menuQLSV.setText("Quản Lý Sinh Viên");
        menuQLSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQLSVActionPerformed(evt);
            }
        });
        jMenu2.add(menuQLSV);

        menuQLD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/List.png"))); // NOI18N
        menuQLD.setText("Quản Lý Điểm");
        menuQLD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQLDActionPerformed(evt);
            }
        });
        jMenu2.add(menuQLD);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Trợ Giúp");

        menuNoiDung.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuNoiDung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-help-about-icon-16.png"))); // NOI18N
        menuNoiDung.setText("Nội Dung");
        menuNoiDung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNoiDungActionPerformed(evt);
            }
        });
        jMenu3.add(menuNoiDung);

        menuGioiThieu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuGioiThieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon-16.png"))); // NOI18N
        menuGioiThieu.setText("Giới Thiệu");
        menuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGioiThieuActionPerformed(evt);
            }
        });
        jMenu3.add(menuGioiThieu);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblVaiTro))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblVaiTro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tbpMain, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void menuNoiDungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNoiDungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuNoiDungActionPerformed

    private void menuThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuThoatActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuThoatActionPerformed

    private void menuQLSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQLSVActionPerformed
        if (qlsv1 == null) {
            qlsv1 = new QLSV1();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/Person-Male-Light-icon-16.png"));
            tbpMain.addTab("Quản Lý Sinh Viên", icon, qlsv1, "Quản Lý Sinh Viên");
        }
        tbpMain.setSelectedComponent(qlsv1);

    }//GEN-LAST:event_menuQLSVActionPerformed

    private void menuQLDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQLDActionPerformed
        if (diem1 == null) {
            diem1 = new QLDiem1();
            ImageIcon icon = new ImageIcon(getClass().getResource("/icon/List.png"));
            tbpMain.addTab("Quản Lý Điểm Sinh Viên", icon, diem1, "Quản Lý Điểm Sinh Viên");
        }
        tbpMain.setSelectedComponent(diem1);
    }//GEN-LAST:event_menuQLDActionPerformed

    private void menuDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDangXuatActionPerformed

    }//GEN-LAST:event_menuDangXuatActionPerformed

    private void tbrDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrDangNhapActionPerformed
        LoginDialog login = new LoginDialog(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_tbrDangNhapActionPerformed

    private void tbrAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbrAboutActionPerformed
        AboutUsDialog aud = new AboutUsDialog(this, true);
        aud.setVisible(true);
    }//GEN-LAST:event_tbrAboutActionPerformed

    private void menuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGioiThieuActionPerformed
        tbrAboutActionPerformed(evt);
    }//GEN-LAST:event_menuGioiThieuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        LoginDialog dialog = new LoginDialog(this, true);
        dialog.setVisible(true);
        LoginSuccessful();
    }//GEN-LAST:event_formWindowOpened

    private void LoginSuccessful(){
        lblName.setText(ShareData.nguoiDangNhap.getTenDangNhap());
        lblVaiTro.setText(ShareData.nguoiDangNhap.getVaiTro());
        if(ShareData.nguoiDangNhap.getVaiTro().equals("GiangVien") ){
            menuQLD.setEnabled(true);
            menuQLSV.setEnabled(false);
            tbpMain.removeAll();
        }else if(ShareData.nguoiDangNhap.getVaiTro().equals("SinhVien")){
            menuQLD.setEnabled(false);
            menuQLSV.setEnabled(false);
        }else if(ShareData.nguoiDangNhap.getVaiTro().equals("DaoTao")){
            menuQLD.setEnabled(false);
            menuQLSV.setEnabled(true);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblVaiTro;
    private javax.swing.JMenuItem menuDangXuat;
    private javax.swing.JMenuItem menuGioiThieu;
    private javax.swing.JMenuItem menuNoiDung;
    private javax.swing.JMenuItem menuQLD;
    private javax.swing.JMenuItem menuQLSV;
    private javax.swing.JMenuItem menuThoat;
    private javax.swing.JTabbedPane tbpMain;
    private javax.swing.JButton tbrAbout;
    private javax.swing.JButton tbrDangNhap;
    // End of variables declaration//GEN-END:variables
}
